import type { Metadata } from 'next'
import { Inter, Poppins, Plus_Jakarta_Sans } from 'next/font/google'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',

})
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '400'],
  variable: '--font-poppins',
})
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <style jsx global>{`
        html {
          font-family: ${poppins.style.fontFamily};
        }
      `}</style> */}
      <body className={`${plusJakartaSans.variable} ${inter.variable} ${poppins.className}`}>{children}</body>
    </html>
  )
}
