#!/usr/bin/env node
import assert from'node:assert/strict';import{readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync}from'node:fs';import{createHash}from'node:crypto';import{tmpdir}from'node:os';import{join}from'node:path';import{spawnSync}from'node:child_process';import{parseUploadOutput,validateCandidateEvidence,validateCandidate,validatePromotion,validateTerminal}from'./foundation-release-contract.mjs';
const sha='1'.repeat(40),tree='2'.repeat(40),archive='3'.repeat(64),manifest='4'.repeat(64),uuid='12345678-1234-4123-8123-123456789abc',baseline='abcdefab-1234-4123-8123-abcdefabcdef',deployment='87654321-4321-4321-8321-cba987654321';const message=`source.sha=${sha} source.tree=${tree} archive.sha256=${archive} input-manifest.sha256=${manifest} provider.byteDigest=N/A_PROVIDER_UNAVAILABLE`,tag=`source-${sha}`;const version={id:uuid,message,tag},status={deploymentId:deployment,versions:[{versionId:baseline,percentage:100}]};
const c={schema:'efolusi.foundation.candidate/v3',source:{sha,tree,githubSha:sha},artifact:{archiveSha256:archive,inputManifestSha256:manifest,uploadInputPath:'.open-next',providerByteDigest:'N/A_PROVIDER_UNAVAILABLE'},toolchain:{node:'22.22.2',pnpm:'10.29.2',wrangler:'4.115.0',checkoutAction:'11d5960a326750d5838078e36cf38b85af677262',pnpmAction:'b906affcce14559ad1aafd4ab0e942779e9f58b1',setupNodeAction:'49933ea5288caeca8642d1e84afbd3f7d6820020',uploadArtifactAction:'ea165f8d65b6e75b540449e92b4886f43607fa02'},upload:{uuid,attempts:1,rc:0,archiveSha256:archive,inputManifestSha256:manifest,outputRows:2,outputSha256:'5'.repeat(64)},providerReadback:{version,rollbackVersion:{id:baseline,message:null,tag:null},deployment:status},preview:{url:'https://candidate.example.workers.dev/',rootCode:307,rootLocation:'/en',rootHeadersSha256:'6'.repeat(64),rootBodySha256:'7'.repeat(64),robotsCode:200,robotsContentType:'text/plain; charset=UTF-8',robotsHeadersSha256:'8'.repeat(64),robotsBodySha256:'9'.repeat(64),e2e:'PASS'},authority:{kind:'protected-dev-push',githubSha:sha},effects:{customer:0,payment:0,productionTraffic:0,deployments:0,settings:0,secrets:0}};const e={githubSha:sha,githubTree:tree,archiveSha256:archive,inputManifestSha256:manifest};assert.equal(validateCandidate(structuredClone(c),e),true);
const alias=`candidate-${sha.slice(0,12)}`;const argv=['versions','upload','--config','wrangler.jsonc','--message',message,'--tag',`source-${sha}`,'--preview-alias',alias];const session={type:'wrangler-session',version:1,wrangler_version:'4.115.0',command_line_args:argv,log_file_path:null,timestamp:'2026-08-26T00:00:00.000Z'},uploaded={type:'version-upload',version:1,worker_name:'efolusi',worker_tag:'5'.repeat(32),version_id:uuid,preview_url:`https://${uuid.slice(0,8)}-efolusi.example.workers.dev/`,preview_alias_url:`https://${alias}-efolusi.example.workers.dev/`,worker_name_overridden:false,timestamp:'2026-08-26T00:00:01.000Z'};
const ndjson=(rows)=>rows.map(x=>JSON.stringify(x)).join('\n')+'\n';assert.deepEqual(parseUploadOutput(ndjson([session,uploaded])),uploaded);assert.deepEqual(parseUploadOutput(ndjson([uploaded,session])),uploaded);
const b=x=>Buffer.from(x),d=x=>createHash('sha256').update(x).digest('hex'),record=b(JSON.stringify(uploaded)+'\n'),raw={'upload-output.ndjson':b(ndjson([session,uploaded])),'upload-record.json':record,'upload-record.recheck.json':record,'preview.status':b('307\n'),'preview.headers':b('HTTP/2 307\r\nlocation: /en\r\n'),'preview.body':b('redirect'),'robots.status':b('200\n'),'robots.headers':b('HTTP/2 200\r\ncontent-type: text/plain; charset=UTF-8\r\n'),'robots.body':b('User-agent: *\n')};const evidenceReceipt=structuredClone(c);evidenceReceipt.upload.outputSha256=d(raw['upload-output.ndjson']);evidenceReceipt.preview.rootHeadersSha256=d(raw['preview.headers']);evidenceReceipt.preview.rootBodySha256=d(raw['preview.body']);evidenceReceipt.preview.robotsHeadersSha256=d(raw['robots.headers']);evidenceReceipt.preview.robotsBodySha256=d(raw['robots.body']);assert.match(validateCandidateEvidence(evidenceReceipt,raw),/upload-output\.ndjson/);for(const name of ['upload-output.ndjson','upload-record.recheck.json','preview.status','preview.headers','preview.body','robots.status','robots.headers','robots.body']){const changed=structuredClone(raw);changed[name]=Buffer.concat([changed[name],b('x')]);assert.throws(()=>validateCandidateEvidence(evidenceReceipt,changed));}
{const changed=structuredClone(raw),receipt=structuredClone(evidenceReceipt);changed['preview.headers']=b('HTTP/2 307\r\nlocation: /id\r\n');receipt.preview.rootHeadersSha256=d(changed['preview.headers']);assert.throws(()=>validateCandidateEvidence(receipt,changed));}{const changed=structuredClone(raw),receipt=structuredClone(evidenceReceipt);changed['robots.headers']=b('HTTP/2 200\r\ncontent-type: text/html\r\n');receipt.preview.robotsHeadersSha256=d(changed['robots.headers']);receipt.preview.robotsContentType='text/html';assert.throws(()=>validateCandidateEvidence(receipt,changed));}{const changed=structuredClone(raw),receipt=structuredClone(evidenceReceipt);changed['robots.body']=b('');receipt.preview.robotsBodySha256=d(changed['robots.body']);assert.throws(()=>validateCandidateEvidence(receipt,changed));}{const changed=structuredClone(raw),forged={...uploaded,worker_tag:'6'.repeat(32)};changed['upload-record.json']=b(JSON.stringify(forged)+'\n');changed['upload-record.recheck.json']=changed['upload-record.json'];assert.throws(()=>validateCandidateEvidence(evidenceReceipt,changed));}
for(const text of [ndjson([session]),ndjson([uploaded]),ndjson([session,session]),ndjson([uploaded,uploaded]),ndjson([session,uploaded,{type:'other'}]),ndjson([session,{...uploaded,version_id:'bad'}]),ndjson([session,{...uploaded,extra:true}]),ndjson([{...session,version:2},uploaded]),'{}\nnot-json\n','{}\n\n{}\n']){assert.throws(()=>parseUploadOutput(text));}
for(const mutate of [
 ([s])=>s.command_line_args[1]='deploy',([s])=>s.command_line_args.splice(2,2),([s])=>s.command_line_args.push('--strict'),([s])=>[s.command_line_args[4],s.command_line_args[6]]=[s.command_line_args[6],s.command_line_args[4]],
 ([s])=>s.command_line_args[7]='source-wrong',([s])=>s.command_line_args[9]='candidate-wrong',([s])=>s.timestamp='not-a-time',([,u])=>u.timestamp='2026-99-99T00:00:00Z',
 ([,u])=>u.worker_name='',([,u])=>u.worker_tag='',([,u])=>u.worker_tag='5'.repeat(31),([,u])=>u.worker_tag='5'.repeat(33),([,u])=>u.worker_tag='g'.repeat(32),([,u])=>u.worker_tag='A'.repeat(32),([,u])=>u.wrangler_environment=null,([,u])=>u.worker_name_overridden=true,([,u])=>delete u.worker_tag,
 ([s,u])=>{s.timestamp='2026-08-26T00:00:02.000Z';u.timestamp='2026-08-26T00:00:01.000Z'},([s,u])=>u.timestamp=s.timestamp,([,u])=>u.timestamp='2026-08-26T00:10:00.001Z',
 ([,u])=>u.preview_alias_url='https://unrelated.example.workers.dev/',([,u])=>u.preview_alias_url=`https://${alias}-wrong.example.workers.dev/`,([,u])=>delete u.preview_alias_url,([,u])=>u.preview_url='https://87654321-efolusi.example.workers.dev/',([,u])=>u.preview_url=u.preview_alias_url,
]){const rows=structuredClone([session,uploaded]);mutate(rows);assert.throws(()=>parseUploadOutput(ndjson(rows)));}
const p={ref:'refs/heads/main',mainSha:'6'.repeat(40),mainTree:tree,candidate:structuredClone(c),freshVersion:structuredClone(version),freshStatus:structuredClone(status),runStartBaseline:baseline,authority:{kind:'protected-main-dispatch',githubSha:'6'.repeat(40)}};assert.deepEqual(validatePromotion(structuredClone(p)),{candidateUuid:uuid,rollbackUuid:baseline});
const ph=(name,id)=>({name,uuid:id,attempts:1,rc:0,activeUuid:id,trafficPercent:100,rootTransportRc:0,robotsTransportRc:0,rootCode:307,rootLocation:'/id',robotsCode:200,robotsContentType:'text/plain',robotsBodySha256:'a'.repeat(64)}),t={schema:'efolusi.foundation.promotion/v3',candidateUuid:uuid,baselineUuid:baseline,rollbackUuid:baseline,phases:[ph('candidate1',uuid),ph('rollback',baseline),ph('candidate2',uuid)],healthEvidenceSha256:'b'.repeat(64),finalState:{deploymentId:deployment,activeVersions:[uuid],candidateTrafficPercent:100},rollback:{armed:true,attempted:0,rc:0,recoveryVerified:0,activeUuid:null},effects:{customer:0,payment:0,settings:0,secrets:0}};assert.equal(validateTerminal(structuredClone(t)),true);
let n=23;function bad(base,fn,validator){const x=structuredClone(base);fn(x);assert.throws(()=>validator(x));n++}for(const f of [x=>x.source.sha='8'.repeat(40),x=>x.source.tree='8'.repeat(40),x=>x.artifact.archiveSha256='3'.repeat(40),x=>x.toolchain.node='20.19.4',x=>x.toolchain.node='22',x=>x.toolchain.pnpmAction='v4',x=>delete x.toolchain.pnpmAction,x=>x.upload.outputRows=1,x=>delete x.upload.outputSha256,x=>x.upload.outputSha256='0'.repeat(63),x=>x.providerReadback.version.id=baseline,x=>x.providerReadback.rollbackVersion.id=uuid,x=>x.providerReadback.rollbackVersion.id='bad',x=>x.providerReadback.rollbackVersion.message=7,x=>x.providerReadback.deployment.versions[0].versionId=uuid,x=>x.providerReadback.deployment.versions[0].percentage=99,x=>x.providerReadback.deployment.versions.push({versionId:baseline,percentage:0}),x=>x.authority.kind='approval-receipt',x=>x.preview.rootCode=200,x=>x.preview.rootLocation='/id',x=>delete x.preview.robotsBodySha256,x=>x.preview.robotsCode=204,x=>x.preview.robotsContentType='text/html',x=>x.preview.e2e='UNKNOWN',x=>x.effects.productionTraffic=1])bad(c,f,x=>validateCandidate(x,e));for(const f of [x=>x.ref='refs/heads/dev',x=>x.freshVersion.id=baseline,x=>x.freshVersion.message='drift',x=>x.freshStatus.versions[0].versionId='fedcbafe-1234-4123-8123-fedcbafedcba',x=>x.freshStatus.versions.push({versionId:baseline,percentage:0}),x=>x.runStartBaseline=uuid,x=>x.authority.kind='external-approval',x=>x.authority.githubSha=sha])bad(p,f,validatePromotion);for(const f of [x=>x.phases=x.phases.slice(0,2),x=>x.phases[0].rootTransportRc=1,x=>x.phases[0].robotsTransportRc=1,x=>x.phases[0].rootCode=200,x=>x.phases[0].rootLocation='/en',x=>x.phases[0].rootLocation='',x=>x.phases[0].rootLocation='https://evil.example/id',x=>x.phases[0].robotsContentType='text/html',x=>x.phases[0].robotsBodySha256='0'.repeat(63),x=>x.healthEvidenceSha256='0'.repeat(63),x=>x.phases[1].rc=1,x=>x.phases[2].activeUuid=baseline,x=>x.rollbackUuid='fedcbafe-1234-4123-8123-fedcbafedcba',x=>x.finalState.activeVersions=[uuid,baseline],x=>x.finalState.deploymentId='bad',x=>{x.rollback.attempted=1;x.rollback.rc=1},x=>{x.rollback.attempted=1;x.rollback.activeUuid=null},x=>delete x.finalState])bad(t,f,validateTerminal);
const sumNames=['candidate-receipt.json','foundation-worker.tgz','input-manifest','preview.body','preview.headers','preview.status','robots.body','robots.headers','robots.status','upload-output.ndjson','upload-record.json','upload-record.recheck.json'],scoped=`cd candidate; test "$(cut -d' ' -f3 SHA256SUMS | LC_ALL=C sort)" = "$(printf '%s\\n' ${sumNames.join(' ')} | LC_ALL=C sort)"; test "$(wc -l < SHA256SUMS | tr -d ' ')" = 12; sha256sum -c SHA256SUMS`;function sumFixture(mode){const root=mkdtempSync(join(tmpdir(),'foundation-sums-')),dir=join(root,'candidate');mkdirSync(dir);for(const n of sumNames)writeFileSync(join(dir,n),n);let lines=sumNames.map(n=>`${d(b(n))}  ${n}`);if(mode==='wrong')lines[0]=`${'0'.repeat(64)}  ${sumNames[0]}`;if(mode==='missing')lines.pop();if(mode==='traversal'){writeFileSync(join(root,'victim'),'victim');lines[0]=`${d(b('victim'))}  ../victim`;}writeFileSync(join(dir,'SHA256SUMS'),lines.join('\n')+'\n');const command=mode==='root'?'sha256sum -c candidate/SHA256SUMS':scoped,result=spawnSync('/bin/bash',['-eu','-c',command],{cwd:root,stdio:'ignore'});rmSync(root,{recursive:true,force:true});return result.status}assert.equal(sumFixture('valid'),0);for(const mode of ['root','wrong','missing','traversal'])assert.notEqual(sumFixture(mode),0);
const w=readFileSync(new URL('../.github/workflows/foundation-release.yml',import.meta.url),'utf8');for(const s of['NODE_VERSION: 22.22.2','node-version: 22.22.2','pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1','run_install: false','push:','branches: [dev]','github.event_name == \'push\'','protected-dev-push','WRANGLER_OUTPUT_FILE_PATH="$PWD/upload-output.ndjson" pnpm','sha256sum -c upload-output.sha256','upload-record.recheck.json','preview.status','robots.status','robots.headers','robots.body','/en"','versions view','deployments status','foundation-release-contract.mjs promotion fresh.json','protected-main-dispatch','if: always()','candidate1','rollback','candidate2',"curl -sS -H 'Cookie: lang=id'",'phase-attempts.ndjson',"trap 'rc=$?; contain \"$rc\"' ERR",'observe "$n" "$id" "$a" "$p" || contain 1','D=$(jq -er .id final.json) || contain 1','post_rc=0','sync phases.ndjson health || post_rc=1','wc -l < health/SHA256SUMS','ACTUAL_HEALTH\" = \"$EXPECTED_HEALTH'])assert.ok(w.includes(s),s);for(const s of['export WRANGLER_OUTPUT_FILE_PATH','20.19.4','node-version: 22\n','corepack prepare','cache: pnpm','options: [candidate, promote]','inputs.action == \'candidate\'','authority_receipt_sha256','authority_expires_at','AUTH_SHA','AUTH_EXPIRY','pull_request:','curl -sS -D "health/$n.root.headers"','set -Eeuo pipefail'])assert.ok(!w.includes(s),s);
{
 const dir=mkdtempSync(join(tmpdir(),'foundation-err-trap-')),marker=join(dir,'rollback');
 const script=`#!/bin/bash\nset -euo pipefail\ncontain(){ trap - ERR INT TERM; printf '%s\\n' rollback > "$1"; exit 23; }\ntrap 'rc=$?; contain "${marker}"' ERR\nfalse\n`;
 const run=spawnSync('/bin/bash',['-c',script],{encoding:'utf8'});assert.equal(run.status,23);assert.equal(readFileSync(marker,'utf8'),'rollback\n');rmSync(dir,{recursive:true,force:true});n++;
}
{
 const dir=mkdtempSync(join(tmpdir(),'foundation-command-substitution-')),marker=join(dir,'rollback');
 const script=`#!/bin/bash\nset -euo pipefail\ncontain(){ trap - ERR INT TERM; printf '%s\\n' rollback >> "$1"; exit 23; }\ntrap 'rc=$?; contain "${marker}"' ERR\nx=$(false)\n`;
 const run=spawnSync('/bin/bash',['-c',script],{encoding:'utf8'});assert.equal(run.status,23);assert.deepEqual(readFileSync(marker,'utf8').trim().split('\n'),['rollback']);rmSync(dir,{recursive:true,force:true});n++;
}
console.log(`PASS positives=7 negatives=${n} static=PASS`);
